// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Post struct {
	ID          int64
	Title       string
	Content     string
	Description string
	CreatedAt   string
	UpdatedAt   sql.NullString
	RemovedAt   sql.NullString
}
